name: Build and Push Docker Image to Google Artifact Registry

on:
  workflow_call:
    inputs:
      gcp-project-id:
        description: 'The GCP project ID'
        required: true
        type: string
      artifact-registry-repo:
        description: 'The Artifact Registry repository name'
        required: true
        type: string
      image-tag:
        description: 'The Docker image tag'
        required: true
        type: string
      dockerfile-path:
        description: 'The path to the Dockerfile'
        required: true
        type: string
      # brand_name:
      #   description: 'Select the brand'
      #   required: true
      #   type: string
      
      IMAGE-ENV: 
        description: "build arg env"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # with:
          # submodules: "true"
          # token: ${{ secrets.CI_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.dockerfile-path }}
          file: ${{ inputs.dockerfile-path }}/Dockerfile
          push: true
          tags: gcr.io/${{ inputs.gcp-project-id }}/${{ inputs.artifact-registry-repo }}:${{ inputs.image-tag }}
          build-args: |
            IMAGE-ENV=${{ inputs.IMAGE-ENV" }}

      - name: Image digest
        run: echo ${{ steps.build-and-push.outputs.digest }} 
